---
- name: Crear el registro DNS del nodo 1
  hosts: all
  connection: local

  tasks:

    - name: Crear el registro DNS {{ hostname_nodo1 }}.{{ dominio_nodos }} - {{ ip_lan_nodo1 }}
      import_tasks: tasks/crear_registro_dns.yml
      vars:
        dns_hostname: "{{ hostname_nodo1 }}.{{ dominio_nodos }}"
        ip_address: "{{ ip_lan_nodo1 | join(' ') }}"

    - name: Crear el registro DNS {{ sql_cluster }}_hb1.{{ dominio_nodos }} - {{ ip_hb_nodo1 }}
      import_tasks: tasks/crear_registro_dns.yml
      vars:
        dns_hostname: "{{ sql_cluster }}_hb1.{{ dominio_nodos }}"
        ip_address: "{{ ip_hb_nodo1 | join(' ') }}"

    - name: Crear el registro DNS {{ sql_cluster }}_backup1.{{ dominio_nodos }} - {{ ip_backup_nodo1 }}
      import_tasks: tasks/crear_registro_dns.yml
      vars:
        dns_hostname: "{{ sql_cluster }}_backup1.{{ dominio_nodos }}"
        ip_address: "{{ ip_backup_nodo1 | join(' ') }}"
